`verbatim` without aesthetics (#652)
So far, anything used in a `mapping` had to have a corresponding
aesthetic mapping entry for the plot type used. All other attributes had
to be passed in `visual`. But that meant that only scalar attributes
could reliably be used via `visual`, as the data in `visual` does not
participate in the grouping & slicing mechanism like the data in
`mapping` does.

This PR changes the rules so that an attribute passed `verbatim`
sidesteps the aesthetics entirely, so no aesthetic mapping needs to be
defined for the plot type for that attribute, which makes it much easier
to pass array attributes through to Makie.

## Before

```julia
mapping(
    1:10,
    1:10,
    layout = repeat(["A", "B"], inner = 5),
    text = string.('A':'J') => verbatim,
    color = RGBf.(range(0, 1, length = 10), 0.5, 0.5) => verbatim,
    fontsize = range(20, 40, length = 10) => verbatim,
    align = tuple.(range(0, 1, length = 10), range(0, 1, length = 10)) => verbatim,
) * visual(Makie.Text) |> draw

ERROR: ArgumentError: ProcessedLayer with plot type MakieCore.Text did not have :fontsize in its AestheticMapping. The mapping was {1 = AlgebraOfGraphics.AesX, 2 = AlgebraOfGraphics.AesY, :text = AlgebraOfGraphics.AesText, :color = AlgebraOfGraphics.AesColor}
```

## After

The attributes without aesthetics can be passed `verbatim` and are
sliced correctly via `layout`.

```julia
mapping(
    1:10,
    1:10,
    layout = repeat(["A", "B"], inner = 5),
    text = string.('A':'J') => verbatim,
    color = RGBf.(range(0, 1, length = 10), 0.5, 0.5) => verbatim,
    fontsize = range(20, 40, length = 10) => verbatim,
    align = tuple.(range(0, 1, length = 10), range(0, 1, length = 10)) => verbatim,
) * visual(Makie.Text) |> draw
```

<img width="516" alt="image"
src="https://github.com/user-attachments/assets/57fdaa4f-4a9f-49ad-93f3-b8c3b7769b3f"
/>