Add `scale` to AesColor scale properties (#700)
## Feature

Allow `colorscale` to be passed as an option to `scales(; Color =
(...))` so things like:

```julia
draw(spec, scales(; Color = (; colorscale = log10)))
```

will work.

## Todo

- [x] get it working for 3-arg heatmap, e.g., `pregrouped(x, y, z) *
visual(Heatmap)`
- [x] get it working for `histogram`, e.g., `data(df) * mapping(:x, :y)
* histogram()`
- [x] docs
- [x] tests

## Usage

Currently got this roughly working now for the first case I think?

```julia-repl
julia> using AlgebraOfGraphics, CairoMakie, Random

julia> Random.seed!(1)
TaskLocalRNG()

julia> x, y = [1:5], [1:7];

julia> z = [rand([1, 1_000, 100_000, 1_000_000], 5, 7)];

julia> spec = pregrouped(x, y, z) * visual(Heatmap)
Layer
  transformation: AlgebraOfGraphics.Visual(Heatmap, {})
  data: AlgebraOfGraphics.Pregrouped
  positional:
    1: UnitRange{Int64}[1:5]
    2: UnitRange{Int64}[1:7]
    3: [[1 1 … 1000000 1000; 1000 1000000 … 1000 1000; … ; 100000 100000 … 1000000 100000; 1000000 1 … 100000 1000]]
  named:

julia> draw(spec, scales(; Color = (; colorscale = log10)))
```

<img width="1200" height="900" alt="display"
src="https://github.com/user-attachments/assets/3c36ee4f-45a8-4807-b828-095820be2386"
/>

```julia-repl
julia> let
           fig, ax, p = heatmap(x[1], y[1], z[1]; colorscale = log10)
           Colorbar(fig[1, 2], p)
           fig
       end
```

<img width="1200" height="900" alt="display"
src="https://github.com/user-attachments/assets/79a66f9b-bf12-427f-bf4e-f8e6c14c7544"
/>

## Motivation, copied from slack

I'm blanking, was it possible to plot heatmaps with logarithmic colors
in AoG before? I can currently do something like:

```julia
plt = data(df) *
    mapping(:x, :y) *
    histogram() *
    visual(colorscale = log10) # or Makie.pseudolog10 if colorrange not defined later

draw(plt, scales(Color = (; colorrange = (1, 10_000)));
     colorbar = (; scale = log10),
)
```

but that requires calling `log10` in two places. Passing it to scales
doesn't seem to be a supported aesthetic attribute,

```julia
plt = data(df) *
    mapping(:x, :y) *
    histogram()

draw(plt, scales(Color = (; colorscale = log10, colorrange = (1, 10_000))))
```

```
ArgumentError: Unknown scale attribute :colorscale for continuous scale with aesthetic AlgebraOfGraphics.AesColor. Available attributes for AlgebraOfGraphics.AesColorContinuousProps are :colormap, :colorrange, :lowclip, :highclip and :nan_color
```

so is this something that I should be passing to mapping somehow
instead? For comparison, this is how I am going about it in vanilla
Makie:

```julia
# Ideally would not have to do this manually
h = fit(Histogram, (df.x, df.y))

fig, ax, hm = heatmap(h; colorscale = log10)

Colorbar(fig[1, 2], hm)

fig
```

**Response from Julius:** This doesn't exist yet but it could be added
here:
https://github.com/MakieOrg/AlgebraOfGraphics.jl/blob/c2751aa2ae907a642b97d64fa5a7802aa572dfbc/src/scales.jl#L380

---------

Co-authored-by: Julius Krumbiegel <22495855+jkrumbiegel@users.noreply.github.com>
Co-authored-by: Julius Krumbiegel <julius.krumbiegel@gmail.com>