Auto categoricals (#681)
This PR makes it more convenient to use the standard forced-categorical
mappings `layout`, `row`, `col` and `group` with data whose type AoG
doesn't consider categorical. Before, we just errored and said "make
your data categorical" but this is a rather redundant step if we know
the only correct answer. Of course, users could inadvertently pass a
completely wrong column with many different float values which gets them
100 facets now, but there's always ways to shoot yourself in the foot if
you're not careful.

It's fairly common to have dataframes with some grouping data in
numerical format. Before, you'd get this:

```julia
df = (; x = 1:10, y = 11:20, group = [1, 2, 3, 2, 3, 2, 1, 1, 2, 3])
data(df) * mapping(:x, :y, layout = :group) * visual(Scatter) |> draw
```

```
ERROR: The `layout` mapping was used with continuous data but can only be used with categorical data. Consider using the `=> nonnumeric` modifier to turn numerical data into categorical.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] (::AlgebraOfGraphics.var"#64#65"{…})(key::Symbol, val::Vector{…})
    @ AlgebraOfGraphics ~/.julia/dev/AlgebraOfGraphics/src/algebra/layer.jl:308
  [3] map!(f::AlgebraOfGraphics.var"#64#65"{…}, out::Dictionaries.Dictionary{…}, d::Dictionaries.Indices{…}, d2::Dictionaries.Dictionary{…})
```

Now, you just get the expected plot directly:

<img width="510" height="382" alt="image"
src="https://github.com/user-attachments/assets/bfce3dea-9fa6-472e-83c9-f6a3260a14cf"
/>

For other aesthetics like color etc. the user is still responsible to
pass the right type themselves, we cannot guess what's intended to be
categorical even though it looks continuous.

This PR also adds a little bit of convenience for another common
situation that was related, where a tuple of columns is passed as a
quick grouping. This used to error:

```julia
df = (; x = 1:10, y = 11:20, group1 = repeat(1:2, inner = 5), group2 = repeat(1:5, 2))
data(df) * mapping(:x, :y, layout = (:group1, :group2)) * visual(Scatter) |> draw
```

```
ERROR: MethodError: no method matching select(::AlgebraOfGraphics.Columns{@NamedTuple{…}}, ::Tuple{Symbol, Symbol})
The function `select` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  select(::Nothing, ::Any, ::Any)
   @ AlgebraOfGraphics ~/.julia/dev/AlgebraOfGraphics/src/algebra/select.jl:66
  select(::AlgebraOfGraphics.Columns, ::Union{AbstractString, Symbol})
```

And now also just works:

<img width="500" height="383" alt="image"
src="https://github.com/user-attachments/assets/97eb066e-a404-4fd6-915a-26d43f3c6b16"
/>