Improve all-missings group handling (#689)
This at least doesn't error if one group contains all missings, I
couldn't change the missings-as-categories behavior for an all-missings
column though.

```julia
df1 = (;
    a = [1, 2, 3],
    b = Union{Float64, Missing}[missing, missing, missing],
)
df2 = (;
    a = [1, 2, 3, 4],
    b = [missing, missing, 3, 4],
    c = ["A", "A", "B", "B"],
)
# this one will fall back to categorical
spec1 = data(df1) * mapping(:a, :b) * visual(Scatter)
# but this one used to error and now doesn't
spec2 = data(df2) * mapping(:a, :b, layout = :c) * visual(Scatter)

f = Figure()
draw!(f[1, 1], spec1)
draw!(f[1, 2], spec2)
f
```

<img width="400" height="389" alt="image"
src="https://github.com/user-attachments/assets/7babe9f7-a3a9-464a-9eb1-2622f751df88"
/>

Before, it would throw 

```
ERROR: MethodError: convert_single_argument(::Vector{Missing}) is ambiguous.
```