catch errors in `_kwdict` and give nice error messages (#630)
Fixes https://github.com/MakieOrg/AlgebraOfGraphics.jl/issues/616

The example from that issue now gives

```julia
julia> draw(..., legend = (position = :bottom))

ERROR: ArgumentError: Can't convert value passed via the keyword `legend` to a
`Dictionary{Symbol,Any}`. If you intended to pass a single-element `NamedTuple`,
check that you didn't write `legend = (key = value)` as this expression resolves to
just `value`. Use either `legend = (; key = value)` or `legend = (key = value,)`.
The invalid value that was passed was:

:bottom

The underlying error message was:

MethodError: no method matching keys(::Symbol)
The function `keys` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  keys(!Matched::Base.TermInfo)
   @ Base terminfo.jl:232
  keys(!Matched::Cmd)
   @ Base process.jl:716
  keys(!Matched::Pkg.Registry.RegistryInstance)
   @ Pkg ~/.julia/juliaup/julia-1.11.4+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/Pkg/src/Registry/registry_instance.jl:449
  ...

Stacktrace:
 [1] _kwdict(prs::Symbol, keyword::Symbol)
   @ AlgebraOfGraphics ~/.julia/dev/AlgebraOfGraphics/src/draw.jl:43
 [2] draw(d::Layer, scales::AlgebraOfGraphics.Scales; axis::@NamedTuple{}, figure::@NamedTuple{}, facet::@NamedTuple{}, legend::Symbol, colorbar::@NamedTuple{}, palette::Nothing)
```

Previously it gave

```
MethodError: no method matching iterate(::Symbol)
The function `iterate` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  iterate(::Layers, Any...)
   @ AlgebraOfGraphics ~/.julia/packages/AlgebraOfGraphics/E0gIq/src/algebra/layers.jl:16
  iterate(::LaTeXStrings.LaTeXString, ::Int64)
   @ LaTeXStrings ~/.julia/packages/LaTeXStrings/6NrIG/src/LaTeXStrings.jl:108
  iterate(::LaTeXStrings.LaTeXString)
   @ LaTeXStrings ~/.julia/packages/LaTeXStrings/6NrIG/src/LaTeXStrings.jl:109
  ...


Stacktrace:
 [1] isempty(itr::Symbol)
   @ Base ./essentials.jl:1121
 [2] _kwdict(prs::Symbol)
   @ AlgebraOfGraphics ~/.julia/packages/AlgebraOfGraphics/E0gIq/src/draw.jl:33
 [3] draw(d::Layer, scales::AlgebraOfGraphics.Scales; axis::@NamedTuple{}, figure::@NamedTuple{size::Tuple{Int64, Int64}}, facet::@NamedTuple{}, legend::Symbol, colorbar::@NamedTuple{}, palette::Nothing)
   @ AlgebraOfGraphics ~/.julia/packages/AlgebraOfGraphics/E0gIq/src/draw.jl:82
 [4] top-level scope
   @ In[32]:3
```